### ISSUE TITLE
Waiting for pixel pegs CPU

### ISSUE THREAD

**Issue by Sal-Tepedino** [Earth34r/afip_last_stand#2]
I suggest a time.sleep(.5) at line 496, though I'm not a python coder.
As it is, it's looping as fast as possible, and soaking up 100% cpu.

**Comment by Earth34r** [comment]
Going to add this in the next commit. In one of our older scripts we did have a small sleep to reduce CPU usage, it didn't make it into this code. Thanks for pointing it out!

**Comment by Sal-Tepedino** [comment]
Good to hear! 

Side note: Currently line 508... after the "Time until next place" line, but I think you figured that out.
